### PR TITLE
Horia's Wcag Viewer

### PR DESCRIPTION
**Pull request by Horiatu**
Checked this version with SortSite checker.

### CODE REVIEW

**Comment by jgravois** [comment]
i'm assuming this was an accident.

**Comment by Horiatu** [comment]
I have done the Pull request according to a conversation with Kelly Hutchins, although It is the first time I'm doing a pull request and I'm not quite sure I've done it well.

Kelly said: "I created a branch for the Esri/Viewer Github repo named WCAG. Can you submit a pull request for your updates to that branch? "

**Comment by jgravois** [comment]
sorry about that!

**Comment by Horiatu** [comment]
Hi Kelly,

Did you have any chance to look to my WCAG Viewer?

Now you may access it directly in development as a Configurable Template in the group “Early Adopter Templates<http://esrica-tsg.maps.arcgis.com/home/group.html?owner=tsg_admin&title=Early%20Adopter%20Templates>“

Note – still in development, the parameters for various colors have no effect yet…

Tx,

Horia Tudosie
Lead Developer, Technology Strategy

Esri Canada
12 Concorde Place, Suite 900
Toronto, ON, M3C 3R8
Direct: 647-943-1841
Office: 416-441-6035 x6641
Fax:    416-441-6838
htudosie@esri.ca<mailto:htudosie@esri.ca>
http://www.esri.ca<http://www.esri.ca/>

**Pull request merged**
